//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_functions.User_functionss {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDateTime", Namespace="http://tempuri.org/", ItemName="dateTime")]
    [System.SerializableAttribute()]
    public class ArrayOfDateTime : System.Collections.Generic.List<System.DateTime> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="User_functionss.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name getUserddataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserddata", ReplyAction="*")]
        User_functions.User_functionss.getUserddataResponse getUserddata(User_functions.User_functionss.getUserddataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserddata", ReplyAction="*")]
        System.Threading.Tasks.Task<User_functions.User_functionss.getUserddataResponse> getUserddataAsync(User_functions.User_functionss.getUserddataRequest request);
        
        // CODEGEN: Generating message contract since element name getUserdbloodResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserdblood", ReplyAction="*")]
        User_functions.User_functionss.getUserdbloodResponse getUserdblood(User_functions.User_functionss.getUserdbloodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserdblood", ReplyAction="*")]
        System.Threading.Tasks.Task<User_functions.User_functionss.getUserdbloodResponse> getUserdbloodAsync(User_functions.User_functionss.getUserdbloodRequest request);
        
        // CODEGEN: Generating message contract since element name getblooddateResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getblooddate", ReplyAction="*")]
        User_functions.User_functionss.getblooddateResponse getblooddate(User_functions.User_functionss.getblooddateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getblooddate", ReplyAction="*")]
        System.Threading.Tasks.Task<User_functions.User_functionss.getblooddateResponse> getblooddateAsync(User_functions.User_functionss.getblooddateRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert", ReplyAction="*")]
        User_functions.User_functionss.insertResponse insert(User_functions.User_functionss.insertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert", ReplyAction="*")]
        System.Threading.Tasks.Task<User_functions.User_functionss.insertResponse> insertAsync(User_functions.User_functionss.insertRequest request);
        
        // CODEGEN: Generating message contract since element name PersonID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserInfo", ReplyAction="*")]
        User_functions.User_functionss.UpdateUserInfoResponse UpdateUserInfo(User_functions.User_functionss.UpdateUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<User_functions.User_functionss.UpdateUserInfoResponse> UpdateUserInfoAsync(User_functions.User_functionss.UpdateUserInfoRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_blood_pressure", ReplyAction="*")]
        User_functions.User_functionss.Update_blood_pressureResponse Update_blood_pressure(User_functions.User_functionss.Update_blood_pressureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_blood_pressure", ReplyAction="*")]
        System.Threading.Tasks.Task<User_functions.User_functionss.Update_blood_pressureResponse> Update_blood_pressureAsync(User_functions.User_functionss.Update_blood_pressureRequest request);
        
        // CODEGEN: Generating message contract since element name PersonId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewUserInfo", ReplyAction="*")]
        User_functions.User_functionss.ViewUserInfoResponse ViewUserInfo(User_functions.User_functionss.ViewUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<User_functions.User_functionss.ViewUserInfoResponse> ViewUserInfoAsync(User_functions.User_functionss.ViewUserInfoRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/check", ReplyAction="*")]
        User_functions.User_functionss.checkResponse check(User_functions.User_functionss.checkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/check", ReplyAction="*")]
        System.Threading.Tasks.Task<User_functions.User_functionss.checkResponse> checkAsync(User_functions.User_functionss.checkRequest request);
        
        // CODEGEN: Generating message contract since element name blood_pressureResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/blood_pressure", ReplyAction="*")]
        User_functions.User_functionss.blood_pressureResponse blood_pressure(User_functions.User_functionss.blood_pressureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/blood_pressure", ReplyAction="*")]
        System.Threading.Tasks.Task<User_functions.User_functionss.blood_pressureResponse> blood_pressureAsync(User_functions.User_functionss.blood_pressureRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserddataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserddata", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.getUserddataRequestBody Body;
        
        public getUserddataRequest() {
        }
        
        public getUserddataRequest(User_functions.User_functionss.getUserddataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUserddataRequestBody {
        
        public getUserddataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserddataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserddataResponse", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.getUserddataResponseBody Body;
        
        public getUserddataResponse() {
        }
        
        public getUserddataResponse(User_functions.User_functionss.getUserddataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserddataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public User_functions.User_functionss.ArrayOfString getUserddataResult;
        
        public getUserddataResponseBody() {
        }
        
        public getUserddataResponseBody(User_functions.User_functionss.ArrayOfString getUserddataResult) {
            this.getUserddataResult = getUserddataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserdbloodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserdblood", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.getUserdbloodRequestBody Body;
        
        public getUserdbloodRequest() {
        }
        
        public getUserdbloodRequest(User_functions.User_functionss.getUserdbloodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUserdbloodRequestBody {
        
        public getUserdbloodRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserdbloodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserdbloodResponse", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.getUserdbloodResponseBody Body;
        
        public getUserdbloodResponse() {
        }
        
        public getUserdbloodResponse(User_functions.User_functionss.getUserdbloodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserdbloodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public User_functions.User_functionss.ArrayOfString getUserdbloodResult;
        
        public getUserdbloodResponseBody() {
        }
        
        public getUserdbloodResponseBody(User_functions.User_functionss.ArrayOfString getUserdbloodResult) {
            this.getUserdbloodResult = getUserdbloodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getblooddateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getblooddate", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.getblooddateRequestBody Body;
        
        public getblooddateRequest() {
        }
        
        public getblooddateRequest(User_functions.User_functionss.getblooddateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getblooddateRequestBody {
        
        public getblooddateRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getblooddateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getblooddateResponse", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.getblooddateResponseBody Body;
        
        public getblooddateResponse() {
        }
        
        public getblooddateResponse(User_functions.User_functionss.getblooddateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getblooddateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public User_functions.User_functionss.ArrayOfDateTime getblooddateResult;
        
        public getblooddateResponseBody() {
        }
        
        public getblooddateResponseBody(User_functions.User_functionss.ArrayOfDateTime getblooddateResult) {
            this.getblooddateResult = getblooddateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.insertRequestBody Body;
        
        public insertRequest() {
        }
        
        public insertRequest(User_functions.User_functionss.insertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int w;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int bp;
        
        public insertRequestBody() {
        }
        
        public insertRequestBody(string id, string password, string name, int age, int w, string gender, int bp) {
            this.id = id;
            this.password = password;
            this.name = name;
            this.age = age;
            this.w = w;
            this.gender = gender;
            this.bp = bp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertResponse", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.insertResponseBody Body;
        
        public insertResponse() {
        }
        
        public insertResponse(User_functions.User_functionss.insertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertResponseBody {
        
        public insertResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.UpdateUserInfoRequestBody Body;
        
        public UpdateUserInfoRequest() {
        }
        
        public UpdateUserInfoRequest(User_functions.User_functionss.UpdateUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PersonID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PersonName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int PersonAge;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int PerosnWeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PerosnGender;
        
        public UpdateUserInfoRequestBody() {
        }
        
        public UpdateUserInfoRequestBody(string PersonID, string pass, string PersonName, int PersonAge, int PerosnWeight, string PerosnGender) {
            this.PersonID = PersonID;
            this.pass = pass;
            this.PersonName = PersonName;
            this.PersonAge = PersonAge;
            this.PerosnWeight = PerosnWeight;
            this.PerosnGender = PerosnGender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.UpdateUserInfoResponseBody Body;
        
        public UpdateUserInfoResponse() {
        }
        
        public UpdateUserInfoResponse(User_functions.User_functionss.UpdateUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserInfoResponseBody {
        
        public UpdateUserInfoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_blood_pressureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_blood_pressure", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.Update_blood_pressureRequestBody Body;
        
        public Update_blood_pressureRequest() {
        }
        
        public Update_blood_pressureRequest(User_functions.User_functionss.Update_blood_pressureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_blood_pressureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int bp;
        
        public Update_blood_pressureRequestBody() {
        }
        
        public Update_blood_pressureRequestBody(string id, string pass, int bp) {
            this.id = id;
            this.pass = pass;
            this.bp = bp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_blood_pressureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_blood_pressureResponse", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.Update_blood_pressureResponseBody Body;
        
        public Update_blood_pressureResponse() {
        }
        
        public Update_blood_pressureResponse(User_functions.User_functionss.Update_blood_pressureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Update_blood_pressureResponseBody {
        
        public Update_blood_pressureResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.ViewUserInfoRequestBody Body;
        
        public ViewUserInfoRequest() {
        }
        
        public ViewUserInfoRequest(User_functions.User_functionss.ViewUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PersonId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passs;
        
        public ViewUserInfoRequestBody() {
        }
        
        public ViewUserInfoRequestBody(string PersonId, string passs) {
            this.PersonId = PersonId;
            this.passs = passs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.ViewUserInfoResponseBody Body;
        
        public ViewUserInfoResponse() {
        }
        
        public ViewUserInfoResponse(User_functions.User_functionss.ViewUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public User_functions.User_functionss.ArrayOfString ViewUserInfoResult;
        
        public ViewUserInfoResponseBody() {
        }
        
        public ViewUserInfoResponseBody(User_functions.User_functionss.ArrayOfString ViewUserInfoResult) {
            this.ViewUserInfoResult = ViewUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="check", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.checkRequestBody Body;
        
        public checkRequest() {
        }
        
        public checkRequest(User_functions.User_functionss.checkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public checkRequestBody() {
        }
        
        public checkRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkResponse", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.checkResponseBody Body;
        
        public checkResponse() {
        }
        
        public checkResponse(User_functions.User_functionss.checkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool checkResult;
        
        public checkResponseBody() {
        }
        
        public checkResponseBody(bool checkResult) {
            this.checkResult = checkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class blood_pressureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="blood_pressure", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.blood_pressureRequestBody Body;
        
        public blood_pressureRequest() {
        }
        
        public blood_pressureRequest(User_functions.User_functionss.blood_pressureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class blood_pressureRequestBody {
        
        public blood_pressureRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class blood_pressureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="blood_pressureResponse", Namespace="http://tempuri.org/", Order=0)]
        public User_functions.User_functionss.blood_pressureResponseBody Body;
        
        public blood_pressureResponse() {
        }
        
        public blood_pressureResponse(User_functions.User_functionss.blood_pressureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class blood_pressureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string blood_pressureResult;
        
        public blood_pressureResponseBody() {
        }
        
        public blood_pressureResponseBody(string blood_pressureResult) {
            this.blood_pressureResult = blood_pressureResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : User_functions.User_functionss.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<User_functions.User_functionss.WebService1Soap>, User_functions.User_functionss.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        User_functions.User_functionss.getUserddataResponse User_functions.User_functionss.WebService1Soap.getUserddata(User_functions.User_functionss.getUserddataRequest request) {
            return base.Channel.getUserddata(request);
        }
        
        public User_functions.User_functionss.ArrayOfString getUserddata() {
            User_functions.User_functionss.getUserddataRequest inValue = new User_functions.User_functionss.getUserddataRequest();
            inValue.Body = new User_functions.User_functionss.getUserddataRequestBody();
            User_functions.User_functionss.getUserddataResponse retVal = ((User_functions.User_functionss.WebService1Soap)(this)).getUserddata(inValue);
            return retVal.Body.getUserddataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<User_functions.User_functionss.getUserddataResponse> User_functions.User_functionss.WebService1Soap.getUserddataAsync(User_functions.User_functionss.getUserddataRequest request) {
            return base.Channel.getUserddataAsync(request);
        }
        
        public System.Threading.Tasks.Task<User_functions.User_functionss.getUserddataResponse> getUserddataAsync() {
            User_functions.User_functionss.getUserddataRequest inValue = new User_functions.User_functionss.getUserddataRequest();
            inValue.Body = new User_functions.User_functionss.getUserddataRequestBody();
            return ((User_functions.User_functionss.WebService1Soap)(this)).getUserddataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        User_functions.User_functionss.getUserdbloodResponse User_functions.User_functionss.WebService1Soap.getUserdblood(User_functions.User_functionss.getUserdbloodRequest request) {
            return base.Channel.getUserdblood(request);
        }
        
        public User_functions.User_functionss.ArrayOfString getUserdblood() {
            User_functions.User_functionss.getUserdbloodRequest inValue = new User_functions.User_functionss.getUserdbloodRequest();
            inValue.Body = new User_functions.User_functionss.getUserdbloodRequestBody();
            User_functions.User_functionss.getUserdbloodResponse retVal = ((User_functions.User_functionss.WebService1Soap)(this)).getUserdblood(inValue);
            return retVal.Body.getUserdbloodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<User_functions.User_functionss.getUserdbloodResponse> User_functions.User_functionss.WebService1Soap.getUserdbloodAsync(User_functions.User_functionss.getUserdbloodRequest request) {
            return base.Channel.getUserdbloodAsync(request);
        }
        
        public System.Threading.Tasks.Task<User_functions.User_functionss.getUserdbloodResponse> getUserdbloodAsync() {
            User_functions.User_functionss.getUserdbloodRequest inValue = new User_functions.User_functionss.getUserdbloodRequest();
            inValue.Body = new User_functions.User_functionss.getUserdbloodRequestBody();
            return ((User_functions.User_functionss.WebService1Soap)(this)).getUserdbloodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        User_functions.User_functionss.getblooddateResponse User_functions.User_functionss.WebService1Soap.getblooddate(User_functions.User_functionss.getblooddateRequest request) {
            return base.Channel.getblooddate(request);
        }
        
        public User_functions.User_functionss.ArrayOfDateTime getblooddate() {
            User_functions.User_functionss.getblooddateRequest inValue = new User_functions.User_functionss.getblooddateRequest();
            inValue.Body = new User_functions.User_functionss.getblooddateRequestBody();
            User_functions.User_functionss.getblooddateResponse retVal = ((User_functions.User_functionss.WebService1Soap)(this)).getblooddate(inValue);
            return retVal.Body.getblooddateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<User_functions.User_functionss.getblooddateResponse> User_functions.User_functionss.WebService1Soap.getblooddateAsync(User_functions.User_functionss.getblooddateRequest request) {
            return base.Channel.getblooddateAsync(request);
        }
        
        public System.Threading.Tasks.Task<User_functions.User_functionss.getblooddateResponse> getblooddateAsync() {
            User_functions.User_functionss.getblooddateRequest inValue = new User_functions.User_functionss.getblooddateRequest();
            inValue.Body = new User_functions.User_functionss.getblooddateRequestBody();
            return ((User_functions.User_functionss.WebService1Soap)(this)).getblooddateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        User_functions.User_functionss.insertResponse User_functions.User_functionss.WebService1Soap.insert(User_functions.User_functionss.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public void insert(string id, string password, string name, int age, int w, string gender, int bp) {
            User_functions.User_functionss.insertRequest inValue = new User_functions.User_functionss.insertRequest();
            inValue.Body = new User_functions.User_functionss.insertRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            inValue.Body.name = name;
            inValue.Body.age = age;
            inValue.Body.w = w;
            inValue.Body.gender = gender;
            inValue.Body.bp = bp;
            User_functions.User_functionss.insertResponse retVal = ((User_functions.User_functionss.WebService1Soap)(this)).insert(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<User_functions.User_functionss.insertResponse> User_functions.User_functionss.WebService1Soap.insertAsync(User_functions.User_functionss.insertRequest request) {
            return base.Channel.insertAsync(request);
        }
        
        public System.Threading.Tasks.Task<User_functions.User_functionss.insertResponse> insertAsync(string id, string password, string name, int age, int w, string gender, int bp) {
            User_functions.User_functionss.insertRequest inValue = new User_functions.User_functionss.insertRequest();
            inValue.Body = new User_functions.User_functionss.insertRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            inValue.Body.name = name;
            inValue.Body.age = age;
            inValue.Body.w = w;
            inValue.Body.gender = gender;
            inValue.Body.bp = bp;
            return ((User_functions.User_functionss.WebService1Soap)(this)).insertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        User_functions.User_functionss.UpdateUserInfoResponse User_functions.User_functionss.WebService1Soap.UpdateUserInfo(User_functions.User_functionss.UpdateUserInfoRequest request) {
            return base.Channel.UpdateUserInfo(request);
        }
        
        public void UpdateUserInfo(string PersonID, string pass, string PersonName, int PersonAge, int PerosnWeight, string PerosnGender) {
            User_functions.User_functionss.UpdateUserInfoRequest inValue = new User_functions.User_functionss.UpdateUserInfoRequest();
            inValue.Body = new User_functions.User_functionss.UpdateUserInfoRequestBody();
            inValue.Body.PersonID = PersonID;
            inValue.Body.pass = pass;
            inValue.Body.PersonName = PersonName;
            inValue.Body.PersonAge = PersonAge;
            inValue.Body.PerosnWeight = PerosnWeight;
            inValue.Body.PerosnGender = PerosnGender;
            User_functions.User_functionss.UpdateUserInfoResponse retVal = ((User_functions.User_functionss.WebService1Soap)(this)).UpdateUserInfo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<User_functions.User_functionss.UpdateUserInfoResponse> User_functions.User_functionss.WebService1Soap.UpdateUserInfoAsync(User_functions.User_functionss.UpdateUserInfoRequest request) {
            return base.Channel.UpdateUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<User_functions.User_functionss.UpdateUserInfoResponse> UpdateUserInfoAsync(string PersonID, string pass, string PersonName, int PersonAge, int PerosnWeight, string PerosnGender) {
            User_functions.User_functionss.UpdateUserInfoRequest inValue = new User_functions.User_functionss.UpdateUserInfoRequest();
            inValue.Body = new User_functions.User_functionss.UpdateUserInfoRequestBody();
            inValue.Body.PersonID = PersonID;
            inValue.Body.pass = pass;
            inValue.Body.PersonName = PersonName;
            inValue.Body.PersonAge = PersonAge;
            inValue.Body.PerosnWeight = PerosnWeight;
            inValue.Body.PerosnGender = PerosnGender;
            return ((User_functions.User_functionss.WebService1Soap)(this)).UpdateUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        User_functions.User_functionss.Update_blood_pressureResponse User_functions.User_functionss.WebService1Soap.Update_blood_pressure(User_functions.User_functionss.Update_blood_pressureRequest request) {
            return base.Channel.Update_blood_pressure(request);
        }
        
        public void Update_blood_pressure(string id, string pass, int bp) {
            User_functions.User_functionss.Update_blood_pressureRequest inValue = new User_functions.User_functionss.Update_blood_pressureRequest();
            inValue.Body = new User_functions.User_functionss.Update_blood_pressureRequestBody();
            inValue.Body.id = id;
            inValue.Body.pass = pass;
            inValue.Body.bp = bp;
            User_functions.User_functionss.Update_blood_pressureResponse retVal = ((User_functions.User_functionss.WebService1Soap)(this)).Update_blood_pressure(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<User_functions.User_functionss.Update_blood_pressureResponse> User_functions.User_functionss.WebService1Soap.Update_blood_pressureAsync(User_functions.User_functionss.Update_blood_pressureRequest request) {
            return base.Channel.Update_blood_pressureAsync(request);
        }
        
        public System.Threading.Tasks.Task<User_functions.User_functionss.Update_blood_pressureResponse> Update_blood_pressureAsync(string id, string pass, int bp) {
            User_functions.User_functionss.Update_blood_pressureRequest inValue = new User_functions.User_functionss.Update_blood_pressureRequest();
            inValue.Body = new User_functions.User_functionss.Update_blood_pressureRequestBody();
            inValue.Body.id = id;
            inValue.Body.pass = pass;
            inValue.Body.bp = bp;
            return ((User_functions.User_functionss.WebService1Soap)(this)).Update_blood_pressureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        User_functions.User_functionss.ViewUserInfoResponse User_functions.User_functionss.WebService1Soap.ViewUserInfo(User_functions.User_functionss.ViewUserInfoRequest request) {
            return base.Channel.ViewUserInfo(request);
        }
        
        public User_functions.User_functionss.ArrayOfString ViewUserInfo(string PersonId, string passs) {
            User_functions.User_functionss.ViewUserInfoRequest inValue = new User_functions.User_functionss.ViewUserInfoRequest();
            inValue.Body = new User_functions.User_functionss.ViewUserInfoRequestBody();
            inValue.Body.PersonId = PersonId;
            inValue.Body.passs = passs;
            User_functions.User_functionss.ViewUserInfoResponse retVal = ((User_functions.User_functionss.WebService1Soap)(this)).ViewUserInfo(inValue);
            return retVal.Body.ViewUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<User_functions.User_functionss.ViewUserInfoResponse> User_functions.User_functionss.WebService1Soap.ViewUserInfoAsync(User_functions.User_functionss.ViewUserInfoRequest request) {
            return base.Channel.ViewUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<User_functions.User_functionss.ViewUserInfoResponse> ViewUserInfoAsync(string PersonId, string passs) {
            User_functions.User_functionss.ViewUserInfoRequest inValue = new User_functions.User_functionss.ViewUserInfoRequest();
            inValue.Body = new User_functions.User_functionss.ViewUserInfoRequestBody();
            inValue.Body.PersonId = PersonId;
            inValue.Body.passs = passs;
            return ((User_functions.User_functionss.WebService1Soap)(this)).ViewUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        User_functions.User_functionss.checkResponse User_functions.User_functionss.WebService1Soap.check(User_functions.User_functionss.checkRequest request) {
            return base.Channel.check(request);
        }
        
        public bool check(string id) {
            User_functions.User_functionss.checkRequest inValue = new User_functions.User_functionss.checkRequest();
            inValue.Body = new User_functions.User_functionss.checkRequestBody();
            inValue.Body.id = id;
            User_functions.User_functionss.checkResponse retVal = ((User_functions.User_functionss.WebService1Soap)(this)).check(inValue);
            return retVal.Body.checkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<User_functions.User_functionss.checkResponse> User_functions.User_functionss.WebService1Soap.checkAsync(User_functions.User_functionss.checkRequest request) {
            return base.Channel.checkAsync(request);
        }
        
        public System.Threading.Tasks.Task<User_functions.User_functionss.checkResponse> checkAsync(string id) {
            User_functions.User_functionss.checkRequest inValue = new User_functions.User_functionss.checkRequest();
            inValue.Body = new User_functions.User_functionss.checkRequestBody();
            inValue.Body.id = id;
            return ((User_functions.User_functionss.WebService1Soap)(this)).checkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        User_functions.User_functionss.blood_pressureResponse User_functions.User_functionss.WebService1Soap.blood_pressure(User_functions.User_functionss.blood_pressureRequest request) {
            return base.Channel.blood_pressure(request);
        }
        
        public string blood_pressure() {
            User_functions.User_functionss.blood_pressureRequest inValue = new User_functions.User_functionss.blood_pressureRequest();
            inValue.Body = new User_functions.User_functionss.blood_pressureRequestBody();
            User_functions.User_functionss.blood_pressureResponse retVal = ((User_functions.User_functionss.WebService1Soap)(this)).blood_pressure(inValue);
            return retVal.Body.blood_pressureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<User_functions.User_functionss.blood_pressureResponse> User_functions.User_functionss.WebService1Soap.blood_pressureAsync(User_functions.User_functionss.blood_pressureRequest request) {
            return base.Channel.blood_pressureAsync(request);
        }
        
        public System.Threading.Tasks.Task<User_functions.User_functionss.blood_pressureResponse> blood_pressureAsync() {
            User_functions.User_functionss.blood_pressureRequest inValue = new User_functions.User_functionss.blood_pressureRequest();
            inValue.Body = new User_functions.User_functionss.blood_pressureRequestBody();
            return ((User_functions.User_functionss.WebService1Soap)(this)).blood_pressureAsync(inValue);
        }
    }
}
